---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_get_auth_invalid"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings"
method: "GET"
auth: "INVALID_AUTH"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
tags:
- "V1"
authors:
- "FX Bot"
category: "UnSecured"
severity: "Major"
inactive: false
policies: null
