---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_put_Anonymous_rbac"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings"
method: "PUT"
auth: "Anonymous"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode == 403"
tags:
- "V1"
authors:
- "FX Bot"
category: "RBAC"
severity: "Critical"
inactive: false
policies: null
