---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_get_query_param_log_forging_pageSize"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings?pageSize=DEBUG:騜"
method: "GET"
auth: "Default"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
tags:
- "V1"
authors:
- "FX Bot"
category: "Functional"
severity: "Major"
inactive: false
policies: null
