---
parent: "api_v1_system-settings_@randominteger"
name: "api_v1_system-settings_@randominteger_get_anonymous_invalid"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings/{{@RandomInteger}}"
method: "GET"
auth: "NONE"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
tags:
- "V1"
authors:
- "FX Bot"
category: "UnSecured"
severity: "Major"
inactive: false
policies: null
